package com.my.edge.common.control;

public enum ControlSignalType {
    REGISTER, UNREGISTER, SUPPLY_DATA, STOP_SUPPLY_DATA, RELEASE_DATA_CHANNEL, REQUEST_DATA, STOP_REQUEST_DATA, REGISTER_JOB, REQUEST_JOB;
}
